//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class additional_events_types
    {
        public long flag { get; set; }
        public string name { get; set; }
        public string short_name { get; set; }
        public string name_in_xml { get; set; }
    }
}
