//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class compdbEntities : DbContext
    {
        public compdbEntities()
            : base("name=compdbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<additional_events_types> additional_events_types { get; set; }
        public virtual DbSet<balls> balls { get; set; }
        public virtual DbSet<coaches> coaches { get; set; }
        public virtual DbSet<descriptions> descriptions { get; set; }
        public virtual DbSet<falsestarts_rules> falsestarts_rules { get; set; }
        public virtual DbSet<grades> grades { get; set; }
        public virtual DbSet<groups> groups { get; set; }
        public virtual DbSet<members> members { get; set; }
        public virtual DbSet<participations> participations { get; set; }
        public virtual DbSet<results_speed> results_speed { get; set; }
        public virtual DbSet<round_dates> round_dates { get; set; }
        public virtual DbSet<rounds> rounds { get; set; }
        public virtual DbSet<teams> teams { get; set; }
    }
}
