//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("compdbModel", "fk_participation_members", "members", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBManager.members), "participations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBManager.participations), true)]
[assembly: EdmRelationshipAttribute("compdbModel", "fk_participation_teams", "teams", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DBManager.teams), "participations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBManager.participations), true)]
[assembly: EdmRelationshipAttribute("compdbModel", "fk_groups_description", "descriptions", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBManager.descriptions), "groups", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBManager.groups), true)]
[assembly: EdmRelationshipAttribute("compdbModel", "fk_participation_groups", "groups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBManager.groups), "participations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBManager.participations), true)]
[assembly: EdmRelationshipAttribute("compdbModel", "fk_round_dates_groups1", "groups", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBManager.groups), "round_dates", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBManager.round_dates), true)]
[assembly: EdmRelationshipAttribute("compdbModel", "fk_participation_coaches", "coaches", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(DBManager.coaches), "participations", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBManager.participations), true)]
[assembly: EdmRelationshipAttribute("compdbModel", "fk_results_speed_participation", "participations", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DBManager.participations), "results_speed", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DBManager.results_speed), true)]

#endregion

namespace DBManager
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class compdbEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new compdbEntities object using the connection string found in the 'compdbEntities' section of the application configuration file.
        /// </summary>
        public compdbEntities() : base("name=compdbEntities", "compdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new compdbEntities object.
        /// </summary>
        public compdbEntities(string connectionString) : base(connectionString, "compdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new compdbEntities object.
        /// </summary>
        public compdbEntities(EntityConnection connection) : base(connection, "compdbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<grades> grades
        {
            get
            {
                if ((_grades == null))
                {
                    _grades = base.CreateObjectSet<grades>("grades");
                }
                return _grades;
            }
        }
        private ObjectSet<grades> _grades;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rounds> rounds
        {
            get
            {
                if ((_rounds == null))
                {
                    _rounds = base.CreateObjectSet<rounds>("rounds");
                }
                return _rounds;
            }
        }
        private ObjectSet<rounds> _rounds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<teams> teams
        {
            get
            {
                if ((_teams == null))
                {
                    _teams = base.CreateObjectSet<teams>("teams");
                }
                return _teams;
            }
        }
        private ObjectSet<teams> _teams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<members> members
        {
            get
            {
                if ((_members == null))
                {
                    _members = base.CreateObjectSet<members>("members");
                }
                return _members;
            }
        }
        private ObjectSet<members> _members;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<descriptions> descriptions
        {
            get
            {
                if ((_descriptions == null))
                {
                    _descriptions = base.CreateObjectSet<descriptions>("descriptions");
                }
                return _descriptions;
            }
        }
        private ObjectSet<descriptions> _descriptions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<participations> participations
        {
            get
            {
                if ((_participations == null))
                {
                    _participations = base.CreateObjectSet<participations>("participations");
                }
                return _participations;
            }
        }
        private ObjectSet<participations> _participations;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<round_dates> round_dates
        {
            get
            {
                if ((_round_dates == null))
                {
                    _round_dates = base.CreateObjectSet<round_dates>("round_dates");
                }
                return _round_dates;
            }
        }
        private ObjectSet<round_dates> _round_dates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<groups> groups
        {
            get
            {
                if ((_groups == null))
                {
                    _groups = base.CreateObjectSet<groups>("groups");
                }
                return _groups;
            }
        }
        private ObjectSet<groups> _groups;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<coaches> coaches
        {
            get
            {
                if ((_coaches == null))
                {
                    _coaches = base.CreateObjectSet<coaches>("coaches");
                }
                return _coaches;
            }
        }
        private ObjectSet<coaches> _coaches;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<results_speed> results_speed
        {
            get
            {
                if ((_results_speed == null))
                {
                    _results_speed = base.CreateObjectSet<results_speed>("results_speed");
                }
                return _results_speed;
            }
        }
        private ObjectSet<results_speed> _results_speed;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<balls> balls
        {
            get
            {
                if ((_balls == null))
                {
                    _balls = base.CreateObjectSet<balls>("balls");
                }
                return _balls;
            }
        }
        private ObjectSet<balls> _balls;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the grades EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogrades(grades grades)
        {
            base.AddObject("grades", grades);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rounds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorounds(rounds rounds)
        {
            base.AddObject("rounds", rounds);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the teams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToteams(teams teams)
        {
            base.AddObject("teams", teams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the members EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomembers(members members)
        {
            base.AddObject("members", members);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the descriptions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTodescriptions(descriptions descriptions)
        {
            base.AddObject("descriptions", descriptions);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the participations EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToparticipations(participations participations)
        {
            base.AddObject("participations", participations);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the round_dates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToround_dates(round_dates round_dates)
        {
            base.AddObject("round_dates", round_dates);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the groups EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogroups(groups groups)
        {
            base.AddObject("groups", groups);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the coaches EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocoaches(coaches coaches)
        {
            base.AddObject("coaches", coaches);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the results_speed EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToresults_speed(results_speed results_speed)
        {
            base.AddObject("results_speed", results_speed);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the balls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToballs(balls balls)
        {
            base.AddObject("balls", balls);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="balls")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class balls : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new balls object.
        /// </summary>
        /// <param name="place">Initial value of the place property.</param>
        /// <param name="value">Initial value of the value property.</param>
        public static balls Createballs(global::System.Byte place, global::System.Byte value)
        {
            balls balls = new balls();
            balls.place = place;
            balls.value = value;
            return balls;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte place
        {
            get
            {
                return _place;
            }
            set
            {
                if (_place != value)
                {
                    OnplaceChanging(value);
                    ReportPropertyChanging("place");
                    _place = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("place");
                    OnplaceChanged();
                }
            }
        }
        private global::System.Byte _place;
        partial void OnplaceChanging(global::System.Byte value);
        partial void OnplaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte value
        {
            get
            {
                return _value;
            }
            set
            {
                OnvalueChanging(value);
                ReportPropertyChanging("value");
                _value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("value");
                OnvalueChanged();
            }
        }
        private global::System.Byte _value;
        partial void OnvalueChanging(global::System.Byte value);
        partial void OnvalueChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="coaches")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class coaches : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new coaches object.
        /// </summary>
        /// <param name="id_coach">Initial value of the id_coach property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static coaches Createcoaches(global::System.Int64 id_coach, global::System.String name)
        {
            coaches coaches = new coaches();
            coaches.id_coach = id_coach;
            coaches.name = name;
            return coaches;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_coach
        {
            get
            {
                return _id_coach;
            }
            set
            {
                if (_id_coach != value)
                {
                    Onid_coachChanging(value);
                    ReportPropertyChanging("id_coach");
                    _id_coach = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_coach");
                    Onid_coachChanged();
                }
            }
        }
        private global::System.Int64 _id_coach;
        partial void Onid_coachChanging(global::System.Int64 value);
        partial void Onid_coachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_participation_coaches", "participations")]
        public EntityCollection<participations> participations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<participations>("compdbModel.fk_participation_coaches", "participations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<participations>("compdbModel.fk_participation_coaches", "participations", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="descriptions")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class descriptions : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new descriptions object.
        /// </summary>
        /// <param name="id_desc">Initial value of the id_desc property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="dir">Initial value of the dir property.</param>
        public static descriptions Createdescriptions(global::System.Int64 id_desc, global::System.String name, global::System.String dir)
        {
            descriptions descriptions = new descriptions();
            descriptions.id_desc = id_desc;
            descriptions.name = name;
            descriptions.dir = dir;
            return descriptions;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_desc
        {
            get
            {
                return _id_desc;
            }
            set
            {
                if (_id_desc != value)
                {
                    Onid_descChanging(value);
                    ReportPropertyChanging("id_desc");
                    _id_desc = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_desc");
                    Onid_descChanged();
                }
            }
        }
        private global::System.Int64 _id_desc;
        partial void Onid_descChanging(global::System.Int64 value);
        partial void Onid_descChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String dir
        {
            get
            {
                return _dir;
            }
            set
            {
                OndirChanging(value);
                ReportPropertyChanging("dir");
                _dir = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("dir");
                OndirChanged();
            }
        }
        private global::System.String _dir;
        partial void OndirChanging(global::System.String value);
        partial void OndirChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_groups_description", "groups")]
        public EntityCollection<groups> groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<groups>("compdbModel.fk_groups_description", "groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<groups>("compdbModel.fk_groups_description", "groups", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="grades")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class grades : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new grades object.
        /// </summary>
        /// <param name="id_grade">Initial value of the id_grade property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static grades Creategrades(global::System.Byte id_grade, global::System.String name)
        {
            grades grades = new grades();
            grades.id_grade = id_grade;
            grades.name = name;
            return grades;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte id_grade
        {
            get
            {
                return _id_grade;
            }
            set
            {
                if (_id_grade != value)
                {
                    Onid_gradeChanging(value);
                    ReportPropertyChanging("id_grade");
                    _id_grade = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_grade");
                    Onid_gradeChanged();
                }
            }
        }
        private global::System.Byte _id_grade;
        partial void Onid_gradeChanging(global::System.Byte value);
        partial void Onid_gradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="groups")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class groups : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new groups object.
        /// </summary>
        /// <param name="id_group">Initial value of the id_group property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="desc">Initial value of the desc property.</param>
        /// <param name="second_col_name">Initial value of the second_col_name property.</param>
        /// <param name="xml_file_name">Initial value of the xml_file_name property.</param>
        /// <param name="sex">Initial value of the sex property.</param>
        /// <param name="comp_start_date">Initial value of the comp_start_date property.</param>
        public static groups Creategroups(global::System.Int64 id_group, global::System.String name, global::System.Int64 desc, global::System.String second_col_name, global::System.String xml_file_name, global::System.Byte sex, global::System.DateTime comp_start_date)
        {
            groups groups = new groups();
            groups.id_group = id_group;
            groups.name = name;
            groups.desc = desc;
            groups.second_col_name = second_col_name;
            groups.xml_file_name = xml_file_name;
            groups.sex = sex;
            groups.comp_start_date = comp_start_date;
            return groups;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_group
        {
            get
            {
                return _id_group;
            }
            set
            {
                if (_id_group != value)
                {
                    Onid_groupChanging(value);
                    ReportPropertyChanging("id_group");
                    _id_group = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_group");
                    Onid_groupChanged();
                }
            }
        }
        private global::System.Int64 _id_group;
        partial void Onid_groupChanging(global::System.Int64 value);
        partial void Onid_groupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> start_year
        {
            get
            {
                return _start_year;
            }
            set
            {
                Onstart_yearChanging(value);
                ReportPropertyChanging("start_year");
                _start_year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("start_year");
                Onstart_yearChanged();
            }
        }
        private Nullable<global::System.Int32> _start_year;
        partial void Onstart_yearChanging(Nullable<global::System.Int32> value);
        partial void Onstart_yearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> end_year
        {
            get
            {
                return _end_year;
            }
            set
            {
                Onend_yearChanging(value);
                ReportPropertyChanging("end_year");
                _end_year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("end_year");
                Onend_yearChanged();
            }
        }
        private Nullable<global::System.Int16> _end_year;
        partial void Onend_yearChanging(Nullable<global::System.Int16> value);
        partial void Onend_yearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 desc
        {
            get
            {
                return _desc;
            }
            set
            {
                OndescChanging(value);
                ReportPropertyChanging("desc");
                _desc = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("desc");
                OndescChanged();
            }
        }
        private global::System.Int64 _desc;
        partial void OndescChanging(global::System.Int64 value);
        partial void OndescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String second_col_name
        {
            get
            {
                return _second_col_name;
            }
            set
            {
                Onsecond_col_nameChanging(value);
                ReportPropertyChanging("second_col_name");
                _second_col_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("second_col_name");
                Onsecond_col_nameChanged();
            }
        }
        private global::System.String _second_col_name;
        partial void Onsecond_col_nameChanging(global::System.String value);
        partial void Onsecond_col_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> from_1_qualif
        {
            get
            {
                return _from_1_qualif;
            }
            set
            {
                Onfrom_1_qualifChanging(value);
                ReportPropertyChanging("from_1_qualif");
                _from_1_qualif = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("from_1_qualif");
                Onfrom_1_qualifChanged();
            }
        }
        private Nullable<global::System.Byte> _from_1_qualif;
        partial void Onfrom_1_qualifChanging(Nullable<global::System.Byte> value);
        partial void Onfrom_1_qualifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> from_2_qualif
        {
            get
            {
                return _from_2_qualif;
            }
            set
            {
                Onfrom_2_qualifChanging(value);
                ReportPropertyChanging("from_2_qualif");
                _from_2_qualif = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("from_2_qualif");
                Onfrom_2_qualifChanged();
            }
        }
        private Nullable<global::System.Byte> _from_2_qualif;
        partial void Onfrom_2_qualifChanging(Nullable<global::System.Byte> value);
        partial void Onfrom_2_qualifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> round_after_qualif
        {
            get
            {
                return _round_after_qualif;
            }
            set
            {
                Onround_after_qualifChanging(value);
                ReportPropertyChanging("round_after_qualif");
                _round_after_qualif = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("round_after_qualif");
                Onround_after_qualifChanged();
            }
        }
        private Nullable<global::System.Byte> _round_after_qualif;
        partial void Onround_after_qualifChanging(Nullable<global::System.Byte> value);
        partial void Onround_after_qualifChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String main_judge
        {
            get
            {
                return _main_judge;
            }
            set
            {
                Onmain_judgeChanging(value);
                ReportPropertyChanging("main_judge");
                _main_judge = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("main_judge");
                Onmain_judgeChanged();
            }
        }
        private global::System.String _main_judge;
        partial void Onmain_judgeChanging(global::System.String value);
        partial void Onmain_judgeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String main_secretary
        {
            get
            {
                return _main_secretary;
            }
            set
            {
                Onmain_secretaryChanging(value);
                ReportPropertyChanging("main_secretary");
                _main_secretary = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("main_secretary");
                Onmain_secretaryChanged();
            }
        }
        private global::System.String _main_secretary;
        partial void Onmain_secretaryChanging(global::System.String value);
        partial void Onmain_secretaryChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String row6
        {
            get
            {
                return _row6;
            }
            set
            {
                Onrow6Changing(value);
                ReportPropertyChanging("row6");
                _row6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("row6");
                Onrow6Changed();
            }
        }
        private global::System.String _row6;
        partial void Onrow6Changing(global::System.String value);
        partial void Onrow6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String xml_file_name
        {
            get
            {
                return _xml_file_name;
            }
            set
            {
                Onxml_file_nameChanging(value);
                ReportPropertyChanging("xml_file_name");
                _xml_file_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("xml_file_name");
                Onxml_file_nameChanged();
            }
        }
        private global::System.String _xml_file_name;
        partial void Onxml_file_nameChanging(global::System.String value);
        partial void Onxml_file_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private global::System.Byte _sex;
        partial void OnsexChanging(global::System.Byte value);
        partial void OnsexChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime comp_start_date
        {
            get
            {
                return _comp_start_date;
            }
            set
            {
                Oncomp_start_dateChanging(value);
                ReportPropertyChanging("comp_start_date");
                _comp_start_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("comp_start_date");
                Oncomp_start_dateChanged();
            }
        }
        private global::System.DateTime _comp_start_date;
        partial void Oncomp_start_dateChanging(global::System.DateTime value);
        partial void Oncomp_start_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> comp_end_date
        {
            get
            {
                return _comp_end_date;
            }
            set
            {
                Oncomp_end_dateChanging(value);
                ReportPropertyChanging("comp_end_date");
                _comp_end_date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("comp_end_date");
                Oncomp_end_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _comp_end_date;
        partial void Oncomp_end_dateChanging(Nullable<global::System.DateTime> value);
        partial void Oncomp_end_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> round_finished_flags
        {
            get
            {
                return _round_finished_flags;
            }
            set
            {
                Onround_finished_flagsChanging(value);
                ReportPropertyChanging("round_finished_flags");
                _round_finished_flags = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("round_finished_flags");
                Onround_finished_flagsChanged();
            }
        }
        private Nullable<global::System.Int32> _round_finished_flags;
        partial void Onround_finished_flagsChanging(Nullable<global::System.Int32> value);
        partial void Onround_finished_flagsChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_groups_description", "descriptions")]
        public descriptions descriptions
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<descriptions>("compdbModel.fk_groups_description", "descriptions").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<descriptions>("compdbModel.fk_groups_description", "descriptions").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<descriptions> descriptionsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<descriptions>("compdbModel.fk_groups_description", "descriptions");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<descriptions>("compdbModel.fk_groups_description", "descriptions", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_participation_groups", "participations")]
        public EntityCollection<participations> participations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<participations>("compdbModel.fk_participation_groups", "participations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<participations>("compdbModel.fk_participation_groups", "participations", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_round_dates_groups1", "round_dates")]
        public EntityCollection<round_dates> round_dates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<round_dates>("compdbModel.fk_round_dates_groups1", "round_dates");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<round_dates>("compdbModel.fk_round_dates_groups1", "round_dates", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="members")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class members : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new members object.
        /// </summary>
        /// <param name="id_member">Initial value of the id_member property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="surname">Initial value of the surname property.</param>
        /// <param name="sex">Initial value of the sex property.</param>
        public static members Createmembers(global::System.Int64 id_member, global::System.String name, global::System.String surname, global::System.Byte sex)
        {
            members members = new members();
            members.id_member = id_member;
            members.name = name;
            members.surname = surname;
            members.sex = sex;
            return members;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_member
        {
            get
            {
                return _id_member;
            }
            set
            {
                if (_id_member != value)
                {
                    Onid_memberChanging(value);
                    ReportPropertyChanging("id_member");
                    _id_member = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_member");
                    Onid_memberChanged();
                }
            }
        }
        private global::System.Int64 _id_member;
        partial void Onid_memberChanging(global::System.Int64 value);
        partial void Onid_memberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String surname
        {
            get
            {
                return _surname;
            }
            set
            {
                OnsurnameChanging(value);
                ReportPropertyChanging("surname");
                _surname = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("surname");
                OnsurnameChanged();
            }
        }
        private global::System.String _surname;
        partial void OnsurnameChanging(global::System.String value);
        partial void OnsurnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> year_of_birth
        {
            get
            {
                return _year_of_birth;
            }
            set
            {
                Onyear_of_birthChanging(value);
                ReportPropertyChanging("year_of_birth");
                _year_of_birth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("year_of_birth");
                Onyear_of_birthChanged();
            }
        }
        private Nullable<global::System.Int16> _year_of_birth;
        partial void Onyear_of_birthChanging(Nullable<global::System.Int16> value);
        partial void Onyear_of_birthChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte sex
        {
            get
            {
                return _sex;
            }
            set
            {
                OnsexChanging(value);
                ReportPropertyChanging("sex");
                _sex = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sex");
                OnsexChanged();
            }
        }
        private global::System.Byte _sex;
        partial void OnsexChanging(global::System.Byte value);
        partial void OnsexChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_participation_members", "participations")]
        public EntityCollection<participations> participations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<participations>("compdbModel.fk_participation_members", "participations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<participations>("compdbModel.fk_participation_members", "participations", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="participations")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class participations : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new participations object.
        /// </summary>
        /// <param name="id_participation">Initial value of the id_participation property.</param>
        /// <param name="member">Initial value of the member property.</param>
        /// <param name="group">Initial value of the Group property.</param>
        public static participations Createparticipations(global::System.Int64 id_participation, global::System.Int64 member, global::System.Int64 group)
        {
            participations participations = new participations();
            participations.id_participation = id_participation;
            participations.member = member;
            participations.Group = group;
            return participations;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_participation
        {
            get
            {
                return _id_participation;
            }
            set
            {
                if (_id_participation != value)
                {
                    Onid_participationChanging(value);
                    ReportPropertyChanging("id_participation");
                    _id_participation = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_participation");
                    Onid_participationChanged();
                }
            }
        }
        private global::System.Int64 _id_participation;
        partial void Onid_participationChanging(global::System.Int64 value);
        partial void Onid_participationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 member
        {
            get
            {
                return _member;
            }
            set
            {
                OnmemberChanging(value);
                ReportPropertyChanging("member");
                _member = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("member");
                OnmemberChanged();
            }
        }
        private global::System.Int64 _member;
        partial void OnmemberChanging(global::System.Int64 value);
        partial void OnmemberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Group
        {
            get
            {
                return _Group;
            }
            set
            {
                OnGroupChanging(value);
                ReportPropertyChanging("Group");
                _Group = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Group");
                OnGroupChanged();
            }
        }
        private global::System.Int64 _Group;
        partial void OnGroupChanging(global::System.Int64 value);
        partial void OnGroupChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> coach
        {
            get
            {
                return _coach;
            }
            set
            {
                OncoachChanging(value);
                ReportPropertyChanging("coach");
                _coach = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("coach");
                OncoachChanged();
            }
        }
        private Nullable<global::System.Int64> _coach;
        partial void OncoachChanging(Nullable<global::System.Int64> value);
        partial void OncoachChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int64> team
        {
            get
            {
                return _team;
            }
            set
            {
                OnteamChanging(value);
                ReportPropertyChanging("team");
                _team = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("team");
                OnteamChanged();
            }
        }
        private Nullable<global::System.Int64> _team;
        partial void OnteamChanging(Nullable<global::System.Int64> value);
        partial void OnteamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> init_grade
        {
            get
            {
                return _init_grade;
            }
            set
            {
                Oninit_gradeChanging(value);
                ReportPropertyChanging("init_grade");
                _init_grade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("init_grade");
                Oninit_gradeChanged();
            }
        }
        private Nullable<global::System.Byte> _init_grade;
        partial void Oninit_gradeChanging(Nullable<global::System.Byte> value);
        partial void Oninit_gradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> result_grade
        {
            get
            {
                return _result_grade;
            }
            set
            {
                Onresult_gradeChanging(value);
                ReportPropertyChanging("result_grade");
                _result_grade = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("result_grade");
                Onresult_gradeChanged();
            }
        }
        private Nullable<global::System.Byte> _result_grade;
        partial void Onresult_gradeChanging(Nullable<global::System.Byte> value);
        partial void Onresult_gradeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> result_place
        {
            get
            {
                return _result_place;
            }
            set
            {
                Onresult_placeChanging(value);
                ReportPropertyChanging("result_place");
                _result_place = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("result_place");
                Onresult_placeChanged();
            }
        }
        private Nullable<global::System.Byte> _result_place;
        partial void Onresult_placeChanging(Nullable<global::System.Byte> value);
        partial void Onresult_placeChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_participation_members", "members")]
        public members members
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<members>("compdbModel.fk_participation_members", "members").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<members>("compdbModel.fk_participation_members", "members").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<members> membersReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<members>("compdbModel.fk_participation_members", "members");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<members>("compdbModel.fk_participation_members", "members", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_participation_teams", "teams")]
        public teams teams
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<teams>("compdbModel.fk_participation_teams", "teams").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<teams>("compdbModel.fk_participation_teams", "teams").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<teams> teamsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<teams>("compdbModel.fk_participation_teams", "teams");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<teams>("compdbModel.fk_participation_teams", "teams", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_participation_groups", "groups")]
        public groups groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<groups>("compdbModel.fk_participation_groups", "groups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<groups>("compdbModel.fk_participation_groups", "groups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<groups> groupsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<groups>("compdbModel.fk_participation_groups", "groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<groups>("compdbModel.fk_participation_groups", "groups", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_participation_coaches", "coaches")]
        public coaches coaches
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<coaches>("compdbModel.fk_participation_coaches", "coaches").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<coaches>("compdbModel.fk_participation_coaches", "coaches").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<coaches> coachesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<coaches>("compdbModel.fk_participation_coaches", "coaches");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<coaches>("compdbModel.fk_participation_coaches", "coaches", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_results_speed_participation", "results_speed")]
        public EntityCollection<results_speed> results_speed
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<results_speed>("compdbModel.fk_results_speed_participation", "results_speed");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<results_speed>("compdbModel.fk_results_speed_participation", "results_speed", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="results_speed")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class results_speed : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new results_speed object.
        /// </summary>
        /// <param name="id_result">Initial value of the id_result property.</param>
        /// <param name="participation">Initial value of the participation property.</param>
        /// <param name="round">Initial value of the round property.</param>
        public static results_speed Createresults_speed(global::System.Int64 id_result, global::System.Int64 participation, global::System.Byte round)
        {
            results_speed results_speed = new results_speed();
            results_speed.id_result = id_result;
            results_speed.participation = participation;
            results_speed.round = round;
            return results_speed;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_result
        {
            get
            {
                return _id_result;
            }
            set
            {
                if (_id_result != value)
                {
                    Onid_resultChanging(value);
                    ReportPropertyChanging("id_result");
                    _id_result = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_result");
                    Onid_resultChanged();
                }
            }
        }
        private global::System.Int64 _id_result;
        partial void Onid_resultChanging(global::System.Int64 value);
        partial void Onid_resultChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 participation
        {
            get
            {
                return _participation;
            }
            set
            {
                OnparticipationChanging(value);
                ReportPropertyChanging("participation");
                _participation = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("participation");
                OnparticipationChanged();
            }
        }
        private global::System.Int64 _participation;
        partial void OnparticipationChanging(global::System.Int64 value);
        partial void OnparticipationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> number
        {
            get
            {
                return _number;
            }
            set
            {
                OnnumberChanging(value);
                ReportPropertyChanging("number");
                _number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("number");
                OnnumberChanged();
            }
        }
        private Nullable<global::System.Byte> _number;
        partial void OnnumberChanging(Nullable<global::System.Byte> value);
        partial void OnnumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte round
        {
            get
            {
                return _round;
            }
            set
            {
                OnroundChanging(value);
                ReportPropertyChanging("round");
                _round = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("round");
                OnroundChanged();
            }
        }
        private global::System.Byte _round;
        partial void OnroundChanging(global::System.Byte value);
        partial void OnroundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> route1
        {
            get
            {
                return _route1;
            }
            set
            {
                Onroute1Changing(value);
                ReportPropertyChanging("route1");
                _route1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("route1");
                Onroute1Changed();
            }
        }
        private Nullable<global::System.TimeSpan> _route1;
        partial void Onroute1Changing(Nullable<global::System.TimeSpan> value);
        partial void Onroute1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> route2
        {
            get
            {
                return _route2;
            }
            set
            {
                Onroute2Changing(value);
                ReportPropertyChanging("route2");
                _route2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("route2");
                Onroute2Changed();
            }
        }
        private Nullable<global::System.TimeSpan> _route2;
        partial void Onroute2Changing(Nullable<global::System.TimeSpan> value);
        partial void Onroute2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> sum
        {
            get
            {
                return _sum;
            }
            set
            {
                OnsumChanging(value);
                ReportPropertyChanging("sum");
                _sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("sum");
                OnsumChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _sum;
        partial void OnsumChanging(Nullable<global::System.TimeSpan> value);
        partial void OnsumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> balls
        {
            get
            {
                return _balls;
            }
            set
            {
                OnballsChanging(value);
                ReportPropertyChanging("balls");
                _balls = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("balls");
                OnballsChanged();
            }
        }
        private Nullable<global::System.Single> _balls;
        partial void OnballsChanging(Nullable<global::System.Single> value);
        partial void OnballsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> place
        {
            get
            {
                return _place;
            }
            set
            {
                OnplaceChanging(value);
                ReportPropertyChanging("place");
                _place = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("place");
                OnplaceChanged();
            }
        }
        private Nullable<global::System.Byte> _place;
        partial void OnplaceChanging(Nullable<global::System.Byte> value);
        partial void OnplaceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> cond_formating_1
        {
            get
            {
                return _cond_formating_1;
            }
            set
            {
                Oncond_formating_1Changing(value);
                ReportPropertyChanging("cond_formating_1");
                _cond_formating_1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cond_formating_1");
                Oncond_formating_1Changed();
            }
        }
        private Nullable<global::System.Byte> _cond_formating_1;
        partial void Oncond_formating_1Changing(Nullable<global::System.Byte> value);
        partial void Oncond_formating_1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> cond_formating_2
        {
            get
            {
                return _cond_formating_2;
            }
            set
            {
                Oncond_formating_2Changing(value);
                ReportPropertyChanging("cond_formating_2");
                _cond_formating_2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cond_formating_2");
                Oncond_formating_2Changed();
            }
        }
        private Nullable<global::System.Byte> _cond_formating_2;
        partial void Oncond_formating_2Changing(Nullable<global::System.Byte> value);
        partial void Oncond_formating_2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Byte> cond_formating_sum
        {
            get
            {
                return _cond_formating_sum;
            }
            set
            {
                Oncond_formating_sumChanging(value);
                ReportPropertyChanging("cond_formating_sum");
                _cond_formating_sum = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("cond_formating_sum");
                Oncond_formating_sumChanged();
            }
        }
        private Nullable<global::System.Byte> _cond_formating_sum;
        partial void Oncond_formating_sumChanging(Nullable<global::System.Byte> value);
        partial void Oncond_formating_sumChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_results_speed_participation", "participations")]
        public participations participations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<participations>("compdbModel.fk_results_speed_participation", "participations").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<participations>("compdbModel.fk_results_speed_participation", "participations").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<participations> participationsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<participations>("compdbModel.fk_results_speed_participation", "participations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<participations>("compdbModel.fk_results_speed_participation", "participations", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="round_dates")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class round_dates : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new round_dates object.
        /// </summary>
        /// <param name="id_round_dates">Initial value of the id_round_dates property.</param>
        /// <param name="round">Initial value of the round property.</param>
        /// <param name="date">Initial value of the date property.</param>
        /// <param name="group">Initial value of the Group property.</param>
        public static round_dates Createround_dates(global::System.Int64 id_round_dates, global::System.Byte round, global::System.String date, global::System.Int64 group)
        {
            round_dates round_dates = new round_dates();
            round_dates.id_round_dates = id_round_dates;
            round_dates.round = round;
            round_dates.date = date;
            round_dates.Group = group;
            return round_dates;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_round_dates
        {
            get
            {
                return _id_round_dates;
            }
            set
            {
                if (_id_round_dates != value)
                {
                    Onid_round_datesChanging(value);
                    ReportPropertyChanging("id_round_dates");
                    _id_round_dates = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_round_dates");
                    Onid_round_datesChanged();
                }
            }
        }
        private global::System.Int64 _id_round_dates;
        partial void Onid_round_datesChanging(global::System.Int64 value);
        partial void Onid_round_datesChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte round
        {
            get
            {
                return _round;
            }
            set
            {
                OnroundChanging(value);
                ReportPropertyChanging("round");
                _round = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("round");
                OnroundChanged();
            }
        }
        private global::System.Byte _round;
        partial void OnroundChanging(global::System.Byte value);
        partial void OnroundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.String _date;
        partial void OndateChanging(global::System.String value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Group
        {
            get
            {
                return _Group;
            }
            set
            {
                OnGroupChanging(value);
                ReportPropertyChanging("Group");
                _Group = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Group");
                OnGroupChanged();
            }
        }
        private global::System.Int64 _Group;
        partial void OnGroupChanging(global::System.Int64 value);
        partial void OnGroupChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_round_dates_groups1", "groups")]
        public groups groups
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<groups>("compdbModel.fk_round_dates_groups1", "groups").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<groups>("compdbModel.fk_round_dates_groups1", "groups").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<groups> groupsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<groups>("compdbModel.fk_round_dates_groups1", "groups");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<groups>("compdbModel.fk_round_dates_groups1", "groups", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="rounds")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rounds : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rounds object.
        /// </summary>
        /// <param name="id_round">Initial value of the id_round property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static rounds Createrounds(global::System.Byte id_round, global::System.String name)
        {
            rounds rounds = new rounds();
            rounds.id_round = id_round;
            rounds.name = name;
            return rounds;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte id_round
        {
            get
            {
                return _id_round;
            }
            set
            {
                if (_id_round != value)
                {
                    Onid_roundChanging(value);
                    ReportPropertyChanging("id_round");
                    _id_round = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_round");
                    Onid_roundChanged();
                }
            }
        }
        private global::System.Byte _id_round;
        partial void Onid_roundChanging(global::System.Byte value);
        partial void Onid_roundChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="compdbModel", Name="teams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class teams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new teams object.
        /// </summary>
        /// <param name="id_team">Initial value of the id_team property.</param>
        /// <param name="name">Initial value of the name property.</param>
        public static teams Createteams(global::System.Int64 id_team, global::System.String name)
        {
            teams teams = new teams();
            teams.id_team = id_team;
            teams.name = name;
            return teams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id_team
        {
            get
            {
                return _id_team;
            }
            set
            {
                if (_id_team != value)
                {
                    Onid_teamChanging(value);
                    ReportPropertyChanging("id_team");
                    _id_team = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id_team");
                    Onid_teamChanged();
                }
            }
        }
        private global::System.Int64 _id_team;
        partial void Onid_teamChanging(global::System.Int64 value);
        partial void Onid_teamChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("compdbModel", "fk_participation_teams", "participations")]
        public EntityCollection<participations> participations
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<participations>("compdbModel.fk_participation_teams", "participations");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<participations>("compdbModel.fk_participation_teams", "participations", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
