//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class falsestarts_rules
    {
        public long id_falsestarts_rules { get; set; }
        public long Group { get; set; }
        public byte start_round { get; set; }
        public byte end_round { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
