//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class participations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public participations()
        {
            this.results_speed = new HashSet<results_speed>();
        }
    
        public long id_participation { get; set; }
        public long member { get; set; }
        public long Group { get; set; }
        public Nullable<long> coach { get; set; }
        public Nullable<long> team { get; set; }
        public Nullable<byte> init_grade { get; set; }
        public Nullable<byte> result_grade { get; set; }
        public Nullable<byte> result_place { get; set; }
    
        public virtual coaches coaches { get; set; }
        public virtual groups groups { get; set; }
        public virtual members members { get; set; }
        public virtual teams teams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<results_speed> results_speed { get; set; }
    }
}
