//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class round_dates
    {
        public long id_round_dates { get; set; }
        public byte round { get; set; }
        public string date { get; set; }
        public long Group { get; set; }
    
        public virtual groups groups { get; set; }
    }
}
