//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager.OnlineDB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class onlineEntities : DbContext
    {
        public onlineEntities()
            : base("name=onlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<events_kind> events_kind { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<participants> participants { get; set; }
        public virtual DbSet<participants_kind> participants_kind { get; set; }
        public virtual DbSet<pupil> pupil { get; set; }
        public virtual DbSet<rang> rang { get; set; }
        public virtual DbSet<results_speed> results_speed { get; set; }
    }
}
