//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager.OnlineDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class participants_kind
    {
        public int participants_id { get; set; }
        public int kind_id { get; set; }
        public Nullable<sbyte> rank { get; set; }
    
        public virtual participants participants { get; set; }
    }
}
