//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBManager.OnlineDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class participants
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public participants()
        {
            this.participants_kind = new HashSet<participants_kind>();
        }
    
        public int id { get; set; }
        public int pupil_id { get; set; }
        public bool status { get; set; }
        public string commet { get; set; }
        public int set { get; set; }
        public int rang_id { get; set; }
        public int competition_id { get; set; }
        public Nullable<int> group_id { get; set; }
        public int user_id { get; set; }
    
        public virtual events events { get; set; }
        public virtual group group { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<participants_kind> participants_kind { get; set; }
        public virtual pupil pupil { get; set; }
        public virtual rang rang { get; set; }
    }
}
